# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=50)),
                ('p_cost', models.IntegerField()),
                ('p_color', models.CharField(max_length=50)),
                ('p_class', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('c_mobile', models.BigIntegerField()),
                ('c_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
